version: 2
environments:
  production:
    buildCommand: npm install && npm run build
    dockerfile: Dockerfile
    routes:
      - src: /
        dest: /app/public
    env:
      - key: APP_KEY
        generate: secret
